
@rootApi=http://localhost:8000
@userApi={{rootApi}}/api/v1/user

@bookApi={{rootApi}}/api/v1/book
###
GET {{rootApi}}

###
GET {{userApi}}/login
Content-Type: application/json

{
    "email":"abcd@gmail.com",
    "password":"1234"
    
}

###
POST {{userApi}}
Content-Type: application/json

{
    "role":"admin",
    "fName":"Andrew",
    "lName":"PP",
    "phone":"983647",
    "address":"somewhere in Sydney",
     "email": "abcd@gmail.com",
     "password":"1234"
}

###
POST {{bookApi}}
Content-Type: application/json

{
     
  "title":"new day",
  "author": "James",
  "year": 2122,
  "thumbnail":"http://ansdnlk.com",
  "summary":"dasoad"
}

###
DELETE {{bookApi}}/64a0eddb5c36c19358893103